service: java-lambda-template

provider:
  name: aws
  runtime: java21
  architecture: arm64
  region: ap-southeast-2
#  memorySize: 7076 # 4 vCPUs
#  memorySize: 5307 # 3 vCPUs
#  memorySize: 3538 # 2 vCPUs
#  memorySize: 1769 # 1 vCPU
  memorySize: 2048 # 2gbs
  profile: personal
  vpc:
    subnetIds:
      - subnet-f4219d9d
      - subnet-06f811b0c1ce1f519
      - subnet-0504f7141af7202d3
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::luketn-java-lambda-template/*"

plugins:
  - serverless-better-credentials

package:
  artifact: target/java-lambda-template.jar

functions:
  main:
    handler: com.luketn.EntryPoint::handleRequest
    environment:
      TEST_BUCKET_NAME: luketn-java-lambda-template
      JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

    events:
      - httpApi:
          method: GET
          path: /
      

